demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls"))
]

demo/polls/urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # create questions
    path("question/", views.question, name="question"),
    path("addQuestion/", views.addQuestion, name="addQuestion"),
]

demo/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    def __str__(self):
        return str(self.question_text)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

demo/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]

    questionsList = Question.objects.all()

    return render(
        request,
        "polls/index.html",
        {
            "latest_question_list": latest_question_list,
            "questionsList": questionsList,
        },
    )


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def question(request):
    return render(
        request,
        "polls/question.html",
        {},
    )


def addQuestion(request):
    print(request.POST)

    return HttpResponse("addQuestion")

demo/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>

	<style>
		html,
		body {
			width: 100%;
		}
		body {
			max-width: 768px;
			margin-inline: auto;
		}
	</style>
	<body>
		<form action="{% url 'polls:vote' question.id %}" method="post">
			{% comment %} for auth reasons {% endcomment %} {% csrf_token %}
			<fieldset>
				<legend><h1>Question: {{ question.question_text }}</h1></legend>
				{% comment %} check for errors {% endcomment %} {% if error_message %}
				<p><strong>{{ error_message }}</strong></p>
				{% endif %} {% comment %} list all of choices {% endcomment %}
				<h2>Choices:</h2>
				{% for choice in question.choice_set.all %}

				<label for="choice{{ forloop.counter }}">
					<input
						type="radio"
						name="choice"
						id="choice{{ forloop.counter }}"
						value="{{ choice.id }}"
					/>
					{{ choice.choice_text }}
				</label>
				<br />
				{% endfor %}
			</fieldset>
			<input type="submit" value="Vote" />
		</form>
	</body>
</html>

demo/polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>

		<link rel="stylesheet" href="{% static 'polls/style.css' %}">
		<link rel="stylesheet" href="{% static 'polls/global.css' %}">
	</head>

	<body>
		<h1 class='font-semibold text-6xl text-red-400' >hello world</h1>

		{% if latest_question_list %}
		<ul>
			{% for question in latest_question_list %}
			<li>
				<a href={% url 'polls:detail' question.id %}> {{ question.question_text }} </a>
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>No polls are available.</p>
		{% endif %}
		<br />
		{% if questionsList %}
		<ul>
			{% for question in questionsList %}
			<li>{{ question.question_text }}-{{ question.pub_date }}</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>No polls are available.</p>
		{% endif %}

		<div class="love">
			<h1 class="love-txt">shrek is love</h1>
		</div>
	</body>
</html>

demo/polls/templates/polls/question.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>

		<link rel="stylesheet" href="{% static 'polls/global.css' %}" />
	</head>

	<body class="w-full max-w-5xl mx-auto">
		<h1 class="font-semibold text-6xl text-red-400">hello question page</h1>

		<form action="{% url 'polls:addQuestion' %}" method="post">
			{% comment %} for auth reasons {% endcomment %} {% csrf_token %}
			<fieldset>
				{% comment %} check for errors {% endcomment %} {% if error_message %}
				<p><strong>{{ error_message }}</strong></p>
				{% endif %} {% comment %} list all of choices {% endcomment %}
				<h2>Question:</h2>
				<input type="text" name="question" />
				<br />
				<h2>Choices:</h2>
				<label>
					choice_1
					<input type="text" name="choice" />
				</label>
				<br />

				<label>
					choice_2
					<input type="text" name="choice" />
				</label>
				<br />

				<label>
					choice_3
					<input type="text" name="choice" />
				</label>
			</fieldset>
			<button
				class="bg-slate-800 text-emerald-300 py-2 px-4 rounded-md"
				type="submit"
			>
				add question
			</button>
		</form>
	</body>
</html>

demo/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>

	<body>
		<h1>{{ question.question_text }}</h1>

		<ul>
			{% for choice in question.choice_set.all %}
			<li>
				{{ choice.choice_text }} -- {{ choice.votes }}
				vote{{choice.votes|pluralize }}
			</li>
			{% endfor %}
		</ul>

		<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
	</body>
</html>